baseURL: "https://easystat.be/"
languageCode: fr-be
paginate: 6
theme: portio-hugo
title: easystat - prof de stat
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
menu:
  main:
    - name: A propos
      url: '#about'
      weight: 1
    - name: Services
      url: '#service'
      weight: 2
    - name: Compétences
      url: '#portfolio'
      weight: 3
    - name: CV
      url: '#resume'
      weight: 4
      
params:
  blogPageURL: blog
  contactLink: contact
  copyright: Antoine Soetewey
  googleAnalytics: G-ECWD38ZTYX
  logo: images/site-navigation/logo.png
  social:
    - icon: fa-linkedin
      url: https://www.linkedin.com/in/antoinesoetewey/
      weight: 1
    - icon: fab fa-github
      url: https://github.com/AntoineSoetewey
      weight: 2
    - icon: fa-twitter
      url: https://twitter.com/statsandr
      weight: 3

markup:
  goldmark:
    renderer:
      unsafe: true
