baseURL: "https://easystat.be/"
languageCode: fr-be
paginate: 6
theme: portio-hugo
title: Portio
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
menu:
  main:
    - name: A propos
      url: '#about'
      weight: 1
    - name: Services
      url: '#service'
      weight: 2
    - name: CV
      url: '#resume'
      weight: 3
    - name: Blog
      url: '#blog'
      weight: 4
  sitemap:
    - name: A propos
      url: '#about'
      weight: 1
    - name: Frequently Ask Question
      url: '#'
      weight: 2
    - name: Privacy & Policy
      url: '#'
      weight: 3
    - name: Latest Article
      url: '#'
      weight: 4
params:
  address:
    address: 23 Khan Niketon, Grand Street, NYK.
    email: hello@example.com
    openingHours: Open from 10am to 6pm (close at 5pm Sundays)
    phone: +(448) 833 5272 332
  blogPageURL: blog
  contactLink: contact
  copyright: Antoine Soetewey
  footerLogo: images/contact/widget-logo.png
  formspreeURL: YOUR FORMSPREE URL
  googleAnalytics: YOUR GOOGLE ANALYTICS CODE
  logo: images/site-navigation/logo.png
  map:
    APIkey: YOUR GOOGLE MAP API
    latitude: '23.7783741'
    longitude: '90.3746808'
    pinImage: images/pin.png
  social:
    - icon: fa-linkedin
      url: https://www.linkedin.com/in/antoinesoetewey/
      weight: 1
    - icon: fab fa-github
      url: https://github.com/AntoineSoetewey
      weight: 2
    - icon: fa-twitter
      url: https://twitter.com/statsandr
      weight: 3

markup:
  goldmark:
    renderer:
      unsafe: true
